name: main.deploy

on:
  push:
    branches: [ "master" ]

jobs:
  deploy-init:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3
      - name: INICIANDO A PUBLICAÇÃO
        run: echo INICIANDO...

      - name: npm install, build, and test
        run: |
            npm install
            npm run build --if-present
            npm run test --if-present

  producao-deploy:
    if: github.ref == 'refs/heads/main'
    needs: [deploy-init]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: INICIANDO A PUBLICAÇÃO PARA PRODUÇÃO
        run: echo INICIANDO...

      - name: Conectar via SSH no servidor de Produção e gerar um backup do projeto atual
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 129.153.83.94
          username: andremenegassi
          password: 12345678
          port: 22
          source: "*"
          target: "/home/andremenegassi/htdocs/www.andremenegassi.com.br"
